# Lock to mpm_prefork only
# This file ensures only one MPM module is loaded
LoadModule mpm_prefork_module modules/mod_mpm_prefork.so

<IfModule mpm_prefork_module>
    StartServers             8
    MinSpareServers          5
    MaxSpareServers         20
    MaxRequestWorkers      256
    MaxConnectionsPerChild   0
</IfModule>
